CREATE TABLE IF NOT EXISTS user
(
    ID        INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    PUBLIC_ID VARCHAR(255)       NOT NULL,
    NAME      VARCHAR(255)       NOT NULL,
    PASSWORD  VARCHAR(255)       NOT NULL
);

CREATE TABLE IF NOT EXISTS user_role
(
    USER VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    primary key (USER, ROLE)
);


